== Introducción al ambiente de JHawanet
=== Que es JHawanetFramework

JHawanetFramework es un software que permite la optimización de redes de distribución de agua potable (RDA), incorporando una serie de problemas y algoritmos metaheurísticos. Adicionalmente, brinda al usuario avanzado la capacidad de extender la aplicación agregando nuevos algoritmos, problemas y operadores.

Junto a lo anteriormente mencionado, JHawanetFramework permite realizar simulaciones hidráulicas utilizando las configuraciones que vienen en el archivo de configuración de red y ver la configuración de los elementos que conforman la red. 

Al momento de realizar la optimización brinda la capacidad de visualizar gráficamente las soluciones. Una vez terminada la simulación, permite seleccionar la solución obtenida para un problema específico y generar un archivo de configuración de red que puede ser abierto en otros ambientes como Epanet o exportar el conjunto de soluciones a un archivo Excel.

JHawanetFramework surge como parte del proyecto Fondecyt Regular N° 1180660 ``Optimization of real-world water distribution systems and hydraulic elements using computational fluid dynamics (cfd) and evolutionary algorithms.'', 2018.

=== Tipos de usuarios

Se contemplan dos tipos de usuarios:

*   Usuarios que trabajan directamente con la aplicación gráfica.
*   Usuarios que utilizan la estructura para acoplar nuevos problemas desde el punto de vista computacional.

=== Objetivo

Este software fue creado con el objetivo de optimizar el diseño y operación de redes de distribución de agua potable, proporcionando dichas capacidades a través de una interfaz gráfica amigable con el usuario. Está basado en la arquitectura lógica del framework multiobjetivo Jmetal implementando una serie de algoritmos metaheurísticos de optimización monoobjetivo y multiobjetivo aplicables en problemas de RDA.

=== Especificaciones técnicas del sistema

El software fue desarrollado bajo el lenguaje de programación Java, utilizando la libreria JavaFX para la creación de la interfaz gráfica. Adicionalente, se hace uso de la librería dinámica link:https://www.epa.gov/water-research/epanet[EpanetToolkit] para realizar las simulaciones hidráulicas sobre las redes de agua potable y evaluar las soluciones generadas por los algoritmos metaheurísticos.

Los algoritmos metaheurísticos implementados, estan basados en aquellos utilizados en la librería link:https://github.com/jMetal/jMetal[JMetal], especificamente la versión 5.9.

Para poder ejecutar la aplicación se tienen los siguientes requisitos:

* Windows 64 bits
* JDK 1.8 64 bits
* Maven

=== Repositorio

El código de la aplicación se encuentra alojado en github en el siguiente enlace: link:https://github.com/EinherjarSt/ProyectoDeMemoria[Repositorio]